### ISSUE TITLE
[UI] Home - pages run out and dont loop

### ISSUE THREAD

**Issue by Enchantress1416** [dylankapnias-uni/miniproject-2023-grp5#141]
![image](https://user-images.githubusercontent.com/91617406/232928864-5ec057dd-04da-4764-860d-49212b7ed8c4.png)

**Comment by Adrian-Hawkins** [comment]
If you drag out side of the mobile view port in your browser then the cards get stuck
This is not an issue as on mobile devices you cannot physically swipe outside the phone
There for this bug will never occur on phones
