### ISSUE TITLE
[UI] Login Page enhancement

### ISSUE THREAD

**Issue by MaverickGDN03** [dylankapnias-uni/miniproject-2023-grp5#176]

**Comment by MaverickGDN03** [comment]
Page is scrollable and scroll bar is visible
![image](https://user-images.githubusercontent.com/83559903/233855631-a48ffd62-9339-4ccf-8023-742de2084d4c.png)

**Comment by MaverickGDN03** [comment]
"Forgot Password " and "Register" are not easily visible
![image](https://user-images.githubusercontent.com/83559903/233855667-45a243ad-aa84-465a-a49a-ba11fccababd.png)

**Comment by yanevdw19021209** [comment]
Fixed
