### ISSUE TITLE
[MEETING] Admin Meeting - 13 March

### ISSUE THREAD

**Issue by ogb-Welsh** [dylankapnias-uni/miniproject-2023-grp5#18]

**Comment by MaverickGDN03** [comment]
• Subsections
		○ User Accounts
		○ User Profiles
		○ Social Activities
		○ Messaging
		○ Feed
	• Five overall sections
		○ Login page 
		○ Homepage
		○ Messages
		○ Posts 
		○ Notifications
		○ Profile
		○ Settings
		
		
		
	• Different sections based off each page 
		○ e.g. home page 
			§ Search bar
			§ Filter
			§ Feed
			§ Profiles
				□ Name 
				□ Age 
		○ Messages
			§ Search
			§ Scroll
			§ Into messages page 
			§ Chat page 
	
	• Final documents
		○ Requirements
		○ Design
		○ Implementation
		○ Testing
		○ Delivery
