### ISSUE TITLE
[Meeting] Liam - 24 March

### ISSUE THREAD

**Issue by ogb-Welsh** [dylankapnias-uni/miniproject-2023-grp5#40]

**Comment by MaverickGDN03** [comment]
Minutes: 
• Don’t need to explain to arne what the system is
• for each person in group saying what they have done at this point / one slide 
• Sweet and simple , just facts 
• Keep to exactly what we done , avoid explaining stuff
• Assume no technical knowledge 
	○ So just explain intro, description, roles, what we have achieved, screenshots of UI pages
	○ Maybe if we have a feature to show him ,
	○ Maybe remove his template and show him our mock ui page
